//! Chat completion response.

use serde::Deserialize;

use super::request::ServiceTier;
use super::message::{Message, ToolCall};

/// Chat completion response.
///
/// See: [API Reference](https://platform.openai.com/docs/api-reference/chat/object)
#[derive(Deserialize, Debug, Clone)]
pub struct Response {

    /// A list of chat completion choices.
    ///
    /// Can be more than one if n is greater than 1.
    pub choices: Vec<Choice>,

    /// The Unix timestamp (in seconds) of when the chat completion
    /// was created.
    pub created: u64,

    /// A unique identifier for the chat completion.
    pub id: String,

    /// The model used for the chat completion.
    pub model: String,

    /// Specifies the processing type used for serving the response.
    pub service_tier: ServiceTier,

    /// Usage statistics for the completion request.
    pub usage: Option<Usage>,
}

impl From<Response> for crate::client::Response {
    fn from(_value: Response) -> Self {
        todo!();
    }
}

/// A chat completion choice.
#[derive(Deserialize, Debug, Clone)]
pub struct Choice {

    /// The index of the choice in the list of choices.
    pub index: i64,

    /// The reason the model stopped generating tokens.
    pub finish_reason: Option<FinishReason>,

    /// A chat completion message generated by the model.
    pub message: Option<Message>,

    /// Streaming delta.
    pub delta: Option<Delta>,
}

/// The reason the model stopped generating tokens.
#[derive(Deserialize, Debug, Clone, Copy)]
#[serde(rename_all = "snake_case")]
pub enum FinishReason {

    /// The model hit a natural stop or a provided stop sequence.
    Stop,

    /// The maximum number of tokens specified in the request was
    /// reached.
    Length,

    /// Content was omitted due to a flag from the content filters.
    ContentFilter,

    /// The model called a tool.
    ToolCalls,

    /// The model called a function.
    #[deprecated]
    FunctionCall,
}

/// A chat completion delta generated by streamed model responses.
///
/// See: [API Reference](https://platform.openai.com/docs/api-reference/chat-streaming/streaming)
#[derive(Deserialize, Debug, Clone)]
pub struct Delta {

    /// The contents of the chunk message.
    pub content: Option<String>,

    /// The refusal message generated by the model.
    pub refusal: Option<String>,

    /// The role of the author of this message.
    pub role: Option<String>,

    /// Tool calls made by the model.
    pub tool_calls: Option<Vec<ToolCall>>,
}

/// Usage statistics for the completion request.
#[derive(Deserialize, Debug, Clone)]
pub struct Usage {

    /// Number of tokens in the generated completion.
    pub completion_tokens: u64,

    /// Number of tokens in the prompt.
    pub prompt_tokens: u64,

    /// Total number of tokens used in the request
    ///
    /// prompt + completion
    pub total_tokens: u64,
}
