//! Message completion request.

use serde::Serialize;

use super::tools::{ToolChoice, McpToolConfig};
use super::message::Message;

/// A request to the messages API.
///
/// See: [API Reference](https://docs.anthropic.com/en/api/messages).
#[derive(Serialize, Debug, Clone)]
pub struct Request {

    /// The model that will complete your prompt.
    pub model: String,

    /// Input messages.
    pub messages: Vec<Message>,

    /// The maximum number of tokens to generate before stopping.
    pub max_tokens: u64,

    /// MCP servers to be utilized in this request.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub mcp_servers: Vec<McpServerUrl>,

    /// Determines whether to use priority capacity (if available) or
    /// standard capacity for this request.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub service_tier: Option<ServiceTier>,

    /// Custom text sequences that will cause the model to stop
    /// generating.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub stop_sequences: Vec<String>,

    /// Whether to incrementally stream the response using server-sent
    /// events.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stream: Option<bool>,

    /// System prompt.
    ///
    /// A system prompt is a way of providing context and instructions
    /// to Claude, such as specifying a particular goal or role.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub system: Option<String>,

    /// Amount of randomness injected into the response.
    ///
    /// Required range: `0 <= x <= 1`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub temperature: Option<f64>,

    /// Configuration for enabling Claude's extended thinking.
    ///
    /// When enabled, responses include thinking content blocks
    /// showing Claude's thinking process before the final
    /// answer. Requires a minimum budget of 1,024 tokens and counts
    /// towards your [`max_tokens`] limit.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thinking: Option<ThinkingConfig>,

    /// How the model should use the provided tools.
    ///
    /// The model can use a specific tool, any available tool, decide
    /// by itself, or not use tools at all.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_choice: Option<ToolChoice>,

    /// Definitions of tools that the model may use.
    ///
    /// If you include tools in your API request, the model may return
    /// `tool_use` content blocks that represent the model's use of
    /// those tools. You can then run those tools using the tool input
    /// generated by the model and then optionally return results back
    /// to the model using `tool_result` content blocks.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub tools: Vec<serde_json::Value>,

    /// Only sample from the top K options for each subsequent token.
    ///
    /// Required range: `x >= 0`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_k: Option<u64>,

    /// Use nucleus sampling.
    ///
    /// Required range: `0 <= x <= 1`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_p: Option<f64>,
}

// Unlike other clients, Anthropic `max_tokens` field is REQUIRED.
// This sets default to 4k - the minimum supported by all models.
impl Default for Request {
    fn default() -> Self {
        Self {
            model: String::default(),
            messages: Vec::default(),
            max_tokens: 4000,
            mcp_servers: Vec::default(),
            service_tier: None,
            stop_sequences: Vec::default(),
            stream: None,
            system: None,
            temperature: None,
            thinking: None,
            tool_choice: None,
            tools: Vec::default(),
            top_k: None,
            top_p: None,
        }
    }
}

impl Request {

    /// Create a [Request] that uses the specified model.
    pub fn from_model(model: &str) -> Self {
        Self { model: model.to_string(), ..Default::default() }
    }

    /// Push a message to the [Request].
    pub fn push_message(self, message: Message) -> Self {
        let mut req = self;
        req.messages.push(message);
        req
    }

    /// Appends a list of messages to the [Request].
    ///
    /// Consumes `messages`.
    pub fn append_messages(self, messages: &mut Vec<Message>) -> Self {
        let mut req = self;
        req.messages.append(messages);
        req
    }

    /// Limit the maximum number of tokens to generate before stopping.
    pub fn max_tokens(self, tokens: u64) -> Self {
        Self { max_tokens: tokens, ..self }
    }

    /// Push an MCP server connection URL to the [Request].
    pub fn push_mcp_server(self, server: McpServerUrl) -> Self {
        let mut req = self;
        req.mcp_servers.push(server);
        req
    }

    /// Append a list of MCP servers to the [Request].
    ///
    /// Consumes `mcp_servers`.
    pub fn append_mcp_servers(self, mcp_servers: &mut Vec<McpServerUrl>) -> Self {
        let mut req = self;
        req.mcp_servers.append(mcp_servers);
        req
    }

    /// Set the [Request] service tier.
    pub fn service_tier(self, tier: ServiceTier) -> Self {
        Self { service_tier: Some(tier), ..self }
    }

    /// Push a stop sequence to the [Request].
    pub fn push_stop_sequence(self, stop_sequence: &str) -> Self {
        let mut req = self;
        req.stop_sequences.push(stop_sequence.to_string());
        req
    }

    /// Append a list of stop sequences to the [Request].
    ///
    /// Consumes `stop_sequences`.
    pub fn append_stop_sequences(self, stop_sequences: &mut Vec<String>) -> Self {
        let mut req = self;
        req.stop_sequences.append(stop_sequences);
        req
    }

    /// Set the [Request] streaming option.
    pub fn stream(self, stream: bool) -> Self {
        Self { stream: Some(stream), ..self }
    }

    /// Set the [Request] system prompt.
    pub fn system(self, prompt: &str) -> Self {
        Self { system: Some(prompt.to_string()), ..self }
    }

    /// Set the [Request] temperature.
    pub fn temperature(self, temp: f64) -> Self {
        Self { temperature: Some(temp), ..self }
    }

    /// Set the [Request] thinking configuration.
    pub fn thinking(self, config: ThinkingConfig) -> Self {
        Self { thinking: Some(config), ..self }
    }

    /// Set the [Request] tool choice configuration.
    pub fn tool_choice(self, tool_choice: ToolChoice) -> Self {
        Self { tool_choice: Some(tool_choice), ..self }
    }

    /// Push a tool to the [Request].
    pub fn push_tool(self, tool: serde_json::Value) -> Self {
        let mut req = self;
        req.tools.push(tool);
        req
    }

    /// Append a list of tools to the [Request].
    pub fn append_tools(self, tools: &mut Vec<serde_json::Value>) -> Self {
        let mut req = self;
        req.tools.append(tools);
        req
    }

    /// Set the `top_k` sampling parameter.
    pub fn top_k(self, top_k: u64) -> Self {
        Self { top_k: Some(top_k), ..self }
    }

    /// Set the `top_p` nucleus sampling parameter.
    pub fn top_p(self, top_p: f64) -> Self {
        Self { top_p: Some(top_p), ..self }
    }
}

/// MCP server connection details.
#[derive(Serialize, Debug, Clone)]
pub struct McpServerUrl {

    /// A name alias for the server.
    pub name: String,

    /// The type of connection details.
    ///
    /// Allowed value: "url".
    #[serde(rename = "type")]
    pub kind: String,

    /// The connection url.
    pub url: String,

    /// An optional authorization token.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub authorization_token: Option<String>,

    /// Optional configuration for calling the server's tools.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub tool_configuration: Option<McpToolConfig>,
}

/// Determines whether to use priority capacity for a [Request].
#[derive(Serialize, Debug, Clone, Copy, Default)]
#[serde(rename_all = "snake_case")]
pub enum ServiceTier {

    /// Automatically decide whether to use priority service.
    #[default]
    Auto,

    /// Only use standard service (never use priority).
    StandardOnly,
}

/// Configuration for enabling Claude's extended thinking.
#[derive(Serialize, Debug, Clone)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum ThinkingConfig {
    Enabled {

        /// Determines how many tokens Claude can use for its internal
        /// reasoning process.
        ///
        /// Larger budgets can enable more thorough analysis for
        /// complex problems, improving response quality.
        ///
        /// Must be `>=1024` and less than
        /// [`max_tokens`](Request::max_tokens).
        budget_tokens: u64,
    },
    Disabled,
}

impl ThinkingConfig {

    /// Create a [ThinkingConfig] with a reasoning budget of
    /// `budget_tokens`.
    pub fn enabled(budget_tokens: u64) -> Self {
        Self::Enabled{budget_tokens}
    }

    /// Disable extended reasoning.
    pub fn disabled() -> Self {
        Self::Disabled
    }
}
