//! Message completion result.

use serde::Deserialize;
use super::message::Content;

/// Message generation response.
///
/// Contains the LLMs response, including tool use, web search, and
/// textual results.
///
/// See: [API Reference](https://docs.claude.com/en/api/messages)
#[derive(Deserialize, Debug, Clone)]
pub struct Response {

    /// Unique object identifier.
    pub id: String,

    /// Conversational role of the generated message.
    ///
    /// This will always be "assistant".
    pub role: String,

    /// Content generated by the model.
    pub content: Content,

    /// The model that handled the request.
    pub model: String,

    /// The reason the model stopped generating tokens.
    ///
    /// In non-streaming mode this value is always non-null. In
    /// streaming mode, it is null in the message_start event and
    /// non-null otherwise.
    pub stop_reason: Option<StopReason>,

    /// Which custom stop sequence was generated, if any.
    ///
    /// This value will be a non-null string if one of your custom
    /// stop sequences was generated.
    pub stop_sequence: Option<String>,

    /// Billing and rate-limit usage.
    pub usage: Usage,
}

/// The reason the model stopped generating tokens.
#[derive(Deserialize, Debug, Clone, Copy)]
#[serde(rename_all = "snake_case")]
pub enum StopReason {

    /// The model reached a natural stopping point
    EndTurn,

    /// [Response] exceeded the requested
    /// [max_tokens](super::Request::max_tokens) or the model's
    /// maximum.
    MaxTokens,

    /// One of the provided
    /// [stop_sequences](super::Request::stop_sequences) was
    /// generated.
    StopSequence,

    /// The model invoked one or more tools.
    ToolUse,

    /// Server automatically paused a long-running turn.
    ///
    /// The response may be provided back as-is in a subsequent
    /// request to let the model continue.
    PauseTurn,

    /// When streaming classifiers intervene to handle potential
    /// policy violations.
    Refusal,
}

/// Model token usage information.
#[derive(Deserialize, Debug, Clone)]
pub struct Usage {

    /// The number of input tokens which were used.
    #[serde(default)]
    pub input_tokens: u64,

    /// The number of output tokens which were used.
    #[serde(default)]
    pub output_tokens: u64,
}
