[package]
name = "renfield"
version = "0.2.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.228", features = ["derive"] }
serde_json = { version = "1.0.145", features = ["arbitrary_precision"] }
thiserror = "2.0.17"
tokio = { version = "1.48.0", features = ["full"] }
reqwest = { version = "0.12.24", features = ["json", "stream"] }
codegen = { path = "../codegen" }
macros = { path = "../macros" }
tokio-stream = "0.1.17"

[dev-dependencies]
dotenv = "0.15.0"
base64 = "0.22.1"
once_cell = "1.21.3"
tokio-shared-rt = "0.1.0"
