[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-get-file",
    "allow-copy-file",
    "allow-move-file",
    "allow-remove-file",
    "allow-create-folder",
    "allow-create-file",
    "allow-list-files",
    "allow-list-bookmarks",
    "allow-create-bookmark",
    "allow-remove-bookmark"
]
