//! Response message content.

use serde::{Serialize, Deserialize};
use super::tools::{FunctionCall, FunctionResponse};

/// Conveniently construct [Gemini](super::Gemini) message content.
pub use macros::gemini_msg as msg;

/// The base structured datatype containing multi-part content of a
/// message.
///
/// A [`Content`] includes a role field designating the producer of
/// the Content and a parts field containing multi-part data that
/// contains the content of the message turn.
///
/// See: [API Reference](https://ai.google.dev/api/caching#Content)
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct Content {

    /// Ordered [Part]s that constitute a single message. Parts may have
    /// different MIME types.
    #[serde(default)]
    pub parts: Vec<Part>,

    /// The producer of the content.
    ///
    /// Must be either 'user' or 'model'. Useful to set for multi-turn
    /// conversations, otherwise can be left blank or unset.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub role: Option<Role>,
}

impl Content {

    /// Combine `self` and `other` into a single [Content],
    /// consuming `other`.
    pub fn combine(self, mut other: Self) -> Self {
        let mut content = self;
        content.parts.append(&mut other.parts);
        content
    }
}

impl From<Part> for Content {
    fn from(part: Part) -> Self {
        Self { role: None, parts: vec![part] }
    }
}

/// [Content] author role.
#[derive(Serialize, Deserialize, Debug, Clone, Copy, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum Role {

    /// [Content] was produced by the user.
    User,

    /// [Content] was produced by the model.
    Model,
}

/// A datatype containing media that is part of a multi-part [Content]
/// message.
///
/// A Part consists of data which has an associated datatype. A Part
/// can only contain one of the accepted types in Part.data.
///
/// A Part must have a fixed IANA MIME type identifying the type and
/// subtype of the media if the inlineData field is filled with raw
/// bytes.
///
/// See: [API Reference](https://ai.google.dev/api/caching#Part)
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Part {

    /// Indicates if the part is thought from the model.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thought: Option<bool>,

    /// An opaque signature for the thought so it can be reused in
    /// subsequent requests.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub thought_signature: Option<String>,

    /// The part's content data.
    #[serde(flatten)]
    pub data: Data,
}

impl From<Data> for Part {
    fn from(data: Data) -> Self {
        Self { thought: None, thought_signature: None, data }
    }
}

impl From<String> for Part {
    fn from(value: String) -> Self {
        Self::from(Data::from(value))
    }
}

impl From<&str> for Part {
    fn from(value: &str) -> Self {
        Self::from(Data::from(value))
    }
}

impl From<Blob> for Part {
    fn from(value: Blob) -> Self {
        Self::from(Data::from(value))
    }
}

impl From<FunctionCall> for Part {
    fn from(value: FunctionCall) -> Self {
        Self::from(Data::from(value))
    }
}

impl From<FunctionResponse> for Part {
    fn from(value: FunctionResponse) -> Self {
        Self::from(Data::from(value))
    }
}

impl From<FileData> for Part {
    fn from(value: FileData) -> Self {
        Self::from(Data::from(value))
    }
}

impl From<ExecutableCode> for Part {
    fn from(value: ExecutableCode) -> Self {
        Self::from(Data::from(value))
    }
}

impl From<CodeExecutionResult> for Part {
    fn from(value: CodeExecutionResult) -> Self {
        Self::from(Data::from(value))
    }
}

/// [Part] data.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub enum Data {

    /// Inline text.
    Text(String),

    /// Inline media bytes.
    InlineData(Blob),

    /// A predicted [FunctionCall]
    /// returned from the model that contains a string representing
    /// the FunctionDeclaration.name with the arguments and their
    /// values.
    FunctionCall(FunctionCall),

    /// Function response.
    ///
    /// The result output of a
    /// [FunctionCall].
    FunctionResponse(FunctionResponse),

    /// URI-based data.
    FileData(FileData),

    /// Code generated by the model that is meant to be executed.
    ExecutableCode(ExecutableCode),

    /// Result of executing the [ExecutableCode].
    CodeExecutionResult(CodeExecutionResult),
}

impl From<String> for Data {
    fn from(value: String) -> Self {
        Self::Text(value)
    }
}

impl From<&str> for Data {
    fn from(value: &str) -> Self {
        Self::Text(value.to_string())
    }
}

impl From<Blob> for Data {
    fn from(value: Blob) -> Self {
        Self::InlineData(value)
    }
}

impl From<FunctionCall> for Data {
    fn from(value: FunctionCall) -> Self {
        Self::FunctionCall(value)
    }
}

impl From<FunctionResponse> for Data {
    fn from(value: FunctionResponse) -> Self {
        Self::FunctionResponse(value)
    }
}

impl From<FileData> for Data {
    fn from(value: FileData) -> Self {
        Self::FileData(value)
    }
}

impl From<ExecutableCode> for Data {
    fn from(value: ExecutableCode) -> Self {
        Self::ExecutableCode(value)
    }
}

impl From<CodeExecutionResult> for Data {
    fn from(value: CodeExecutionResult) -> Self {
        Self::CodeExecutionResult(value)
    }
}

/// Raw media bytes.
///
/// Text should not be sent as raw bytes, use the 'text' field.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Blob {

    /// The IANA standard MIME type of the source data.
    pub mime_type: String,

    /// Raw bytes for media formats.
    ///
    /// A base64-encoded string.
    pub data: String,
}

impl Blob {

    /// Create a new [Blob].
    pub fn new(mime_type: &str, data: &str) -> Self {
        Self { mime_type: mime_type.to_string(), data: data.to_string() }
    }
}

/// URI based data.
///
/// See: [API Reference](https://ai.google.dev/api/caching#FileData)
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct FileData {

    /// The IANA standard MIME type of the source data.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mime_type: Option<String>,

    /// Data URI.
    pub file_uri: String,
}

impl FileData {

    /// Create a new [FileData] instance.
    pub fn new(mime_type: Option<&str>, file_uri: &str) -> Self {
        let mime_type = mime_type.map(|v| v.to_string());
        Self { mime_type, file_uri: file_uri.to_string() }
    }
}

/// Code generated by the model that is meant to be executed.
///
/// See: [API Reference](https://ai.google.dev/api/caching#ExecutableCode)
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ExecutableCode {

    /// Programming language of the code.
    pub language: String,

    /// The code to be executed.
    pub code: String,
}

/// Result of executing the [ExecutableCode].
///
/// See: [API Reference](https://ai.google.dev/api/caching#CodeExecutionResult)
#[derive(Serialize, Deserialize, Debug, Clone)]
pub struct CodeExecutionResult {

    /// Outcome of the code execution.
    pub outcome: Outcome,

    /// Contains stdout when code execution is successful, stderr or
    /// other description otherwise.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub output: Option<String>,
}

/// Enumeration of possible outcomes of the code execution.
///
/// See: [API Reference](https://ai.google.dev/api/caching#Outcome)
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Outcome {

    /// Code execution completed successfully.
    OutcomeOk,

    /// Code execution finished but with a failure. stderr should
    /// contain the reason.
    OutcomeFailed,

    /// Code execution ran for too long, and was cancelled. There may
    /// or may not be a partial output present.
    OutcomeDeadlineExceeded,
}

#[cfg(test)]
mod tests {

    #[allow(unused_imports)]
    use crate as renfield;

    use crate::client::gemini::*;
    use serde_json::{to_value, json};

    #[test]
    fn test_msg_text() {
        let msg = msg!("user", "plain text");
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{"text": "plain text"}],
            "role": "user",
        }));
        let msg = msg!("model", "plain text");
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{"text": "plain text"}],
            "role": "model",
        }));
    }

    #[test]
    fn test_msg_multipart_text() {
        let msg = msg!("user", "paragraph 0", "paragraph 1");
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [
                {"text": "paragraph 0"},
                {"text": "paragraph 1"},
            ],
            "role": "user",
        }));
        let msg = msg!("model", "paragraph 0", "paragraph 1");
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [
                {"text": "paragraph 0"},
                {"text": "paragraph 1"},
            ],
            "role": "model",
        }));
    }

    #[test]
    fn test_msg_inline_data() {
        let msg = msg!("user", Blob::new("text/plain", "hello world"));
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "inlineData": {
                    "mimeType": "text/plain",
                    "data": "hello world",
                },
            }],
            "role": "user",
        }));
        let msg = msg!("model", Blob::new("text/plain", "hello world"));
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "inlineData": {
                    "mimeType": "text/plain",
                    "data": "hello world",
                },
            }],
            "role": "model",
        }));
    }

    #[test]
    fn test_msg_function_call() {
        let function_call = FunctionCall{
            id: None,
            name: "my_func".to_string(),
            args: Some(json!({ "type": "string" })),
        };
        let msg = msg!("user",function_call.clone());
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "functionCall": {
                    "name": "my_func",
                    "args": { "type": "string" },
                },
            }],
            "role": "user",
        }));
        let msg = msg!("model", function_call);
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "functionCall": {
                    "name": "my_func",
                    "args": { "type": "string" },
                },
            }],
            "role": "model",
        }));
    }

    #[test]
    fn test_msg_function_response() {
        let function_response = FunctionResponse {
            id: None,
            name: "my_func".to_string(),
            response: json!(3.14159),
        };
        let msg = msg!("user", function_response.clone());
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "functionResponse": {
                    "name": "my_func",
                    "response": 3.14159,
                },
            }],
            "role": "user",
        }));
        let msg = msg!("model", function_response);
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "functionResponse": {
                    "name": "my_func",
                    "response": 3.14159,
                },
            }],
            "role": "model",
        }));
    }

    #[test]
    fn test_msg_file_data() {
        let msg = msg!("user", FileData::new(Some("text/plain"), "uri"));
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "fileData": {
                    "mimeType": "text/plain",
                    "fileUri": "uri",
                },
            }],
            "role": "user",
        }));
        let msg = msg!("model", FileData::new(Some("text/plain"), "uri"));
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "fileData": {
                    "mimeType": "text/plain",
                    "fileUri": "uri",
                },
            }],
            "role": "model",
        }));
    }

    #[test]
    fn test_msg_executable_code() {
        let executable_code = ExecutableCode {
            language: "python".to_string(),
            code: "print('hello')".to_string(),
        };
        let msg = msg!("user", executable_code.clone());
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "executableCode": {
                    "language": "python",
                    "code": "print('hello')",
                },
            }],
            "role": "user",
        }));
        let msg = msg!("model", executable_code);
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "executableCode": {
                    "language": "python",
                    "code": "print('hello')",
                },
            }],
            "role": "model",
        }));
    }

    #[test]
    fn test_msg_code_execution_result() {
        let execution_result = CodeExecutionResult {
            outcome: Outcome::OutcomeOk,
            output: Some("hello".to_string()),
        };
        let msg = msg!("user", execution_result.clone());
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "codeExecutionResult": {
                    "outcome": "OUTCOME_OK",
                    "output": "hello",
                },
            }],
            "role": "user",
        }));
        let msg = msg!("model", execution_result);
        assert_eq!(to_value(msg).unwrap(), json!({
            "parts": [{
                "codeExecutionResult": {
                    "outcome": "OUTCOME_OK",
                    "output": "hello",
                },
            }],
            "role": "model",
        }));
    }
}
