//! Generation response.

use serde::Deserialize;

use super::content::Content;
use super::safety::SafetyRating;

/// Response from the model supporting multiple candidate responses.
///
/// See: [API Reference](https://ai.google.dev/api/generate-content#generatecontentresponse)
#[derive(Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Response {

    /// Candidate responses from the model.
    pub candidates: Vec<Candidate>,

    /// Metadata on the generation requests' token usage.
    pub usage_metadata: UsageMetadata,

    /// The model version used to generate the response.
    pub model_version: String,

    /// Identifier used to identify each response.
    pub response_id: String,
}

/// A response candidate generated from the model.
///
/// See: [API Reference](https://ai.google.dev/api/generate-content#candidate)
#[derive(Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Candidate {

    /// Generated content returned from the model.
    pub content: Content,

    /// The reason why the model stopped generating tokens.
    ///
    /// If empty, the model has not stopped generating tokens.
    pub finish_reason: Option<FinishReason>,

    /// List of ratings for the safety of a response candidate.
    ///
    /// There is at most one rating per category.
    #[serde(default)]
    pub safety_ratings: Vec<SafetyRating>,

    /// Token count for this candidate.
    pub token_count: Option<u64>,

    /// Average log probability score of the candidate.
    pub avg_logprobs: Option<f64>,

    /// Index of the candidate in the list of response candidates.
    pub index: u64,

    /// Details the reason why the model stopped generating tokens.
    ///
    /// This is populated only when [`finish_reason`] is set.
    pub finish_message: Option<String>,
}

/// Defines the reason why the model stopped generating tokens.
///
/// See: [API Reference](https://ai.google.dev/api/generate-content#FinishReason)
#[derive(Deserialize, Debug, Clone)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FinishReason {

    /// Natural stop point of the model or provided stop sequence.
    Stop,

    /// The maximum number of tokens as specified in the request was
    /// reached.
    MaxTokens,

    /// The response candidate content was flagged for safety reasons.
    Safety,

    /// The response candidate content was flagged for recitation
    /// reasons.
    Recitation,

    /// The response candidate content was flagged for using an
    /// unsupported language.
    Language,

    /// Unknown reason.
    Other,

    /// Token generation stopped because the content contains
    /// forbidden terms.
    Blocklist,

    /// Token generation stopped for potentially containing prohibited
    /// content.
    ProhibitedContent,

    /// Token generation stopped because the content potentially
    /// contains Sensitive Personally Identifiable Information (SPII).
    Spii,

    /// The function call generated by the model is invalid.
    MalformedFunctionCall,

    /// Token generation stopped because generated images contain
    /// safety violations.
    ImageSafety,

    /// Image generation stopped because generated images has other
    /// prohibited content.
    ImageProhibitedContent,

    /// Image generation stopped because of other miscellaneous issue.
    ImageOther,

    /// The model was expected to generate an image, but none was
    /// generated.
    NoImage,

    /// Image generation stopped due to recitation.
    ImageRecitation,

    /// Model generated a tool call but no tools were enabled in the
    /// request.
    UnexpectedToolCall,

    /// Model called too many tools consecutively, thus the system
    /// exited execution.
    TooManyToolCalls,
}

/// Metadata on the generation request's token usage.
///
/// See: [API Reference](https://ai.google.dev/api/generate-content#UsageMetadata)
#[derive(Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct UsageMetadata {

    /// Number of tokens in the prompt.
    pub prompt_token_count: u64,

    /// Number of tokens in the cached part of the prompt.
    pub cached_content_token_count: Option<u64>,

    /// Total number of tokens across all the generated response
    /// candidates.
    pub candidates_token_count: Option<u64>,

    /// Number of tokens present in tool-use prompt(s).
    pub tool_use_prompt_token_count: Option<u64>,

    /// Number of tokens of thoughts for thinking models.
    pub thoughts_token_count: Option<u64>,

    /// Total token count for the generation request (prompt +
    /// response candidates).
    pub total_token_count: u64,
}
