//! Tool declaration and configuration params.

use serde::{Serialize, Deserialize};

/// Tool details that the model may use to generate response.
///
/// A Tool is a piece of code that enables the system to interact with
/// external systems to perform an action, or set of actions, outside
/// of knowledge and scope of the model.
///
/// See: [API Reference](https://ai.google.dev/api/caching#Tool)
#[derive(Serialize, Debug, Clone, Default)]
#[serde(rename_all = "camelCase")]
pub struct Tool {

    /// A list of [FunctionDeclaration] available to the model that can
    /// be used for function calling.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub function_declarations: Vec<serde_json::Value>,

    /// Enables the model to execute code as part of generation.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub code_execution: Option<CodeExecution>,

    /// [GoogleSearch] tool type.
    ///
    /// Tool to support Google Search in Model. Powered by Google.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub google_search: Option<GoogleSearch>,

    /// Tool to support the model interacting directly with the
    /// computer.
    ///
    /// If enabled, it automatically populates computer-use specific
    /// Function Declarations.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub computer_use: Option<ComputerUse>,

    /// Tool to support URL context retrieval.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub url_context: Option<UrlContext>,

    /// FileSearch tool type.
    ///
    /// Tool to retrieve knowledge from Semantic Retrieval corpora.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub file_search: Option<FileSearch>,

    /// Tool that allows grounding the model's response with
    /// geospatial context related to the user's query.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub google_maps: Option<GoogleMaps>,
}

impl From<serde_json::Value> for Tool {
    fn from(schema: serde_json::Value) -> Self {
        let mut tool = Tool::default();
        tool.function_declarations.push(schema);
        tool
    }
}

impl Tool {

    /// Create a [Tool] that enables remote code execution.
    ///
    /// See also: [CodeExecution].
    pub fn code_execution() -> Self {
        Self { code_execution: Some(CodeExecution{}), ..Self::default() }
    }

    /// Create a [Tool] that enables Google Search grounding.
    ///
    /// See also: [GoogleSearch].
    pub fn google_search(time_range_filter: Option<Interval>) -> Self {
        Self {
            google_search: Some(GoogleSearch {time_range_filter}),
            ..Self::default()
        }
    }

    /// Creates a [Tool] that handles URL context retrieval.
    pub fn url_context() -> Self {
        Self { url_context: Some(UrlContext {}), ..Self::default() }
    }

    /// Creates a [Tool] that handles file search.
    pub fn file_search() -> Self {
        todo!();
    }

    /// Creates a [Tool] that grounds the model's responses with
    /// geospatial context.
    ///
    /// See also: [GoogleMaps].
    ///
    /// Optionally provide the relevant location context by specifying
    /// the `lat_lng` coordinates in [RetrievalConfig].
    pub fn google_maps(enable_widget: Option<bool>) -> Self {
        Self {
            google_maps: Some(GoogleMaps{ enable_widget }),
            ..Self::default()
        }
    }
}

/// Tool that executes code generated by the model, and automatically
/// returns the result to the model.
///
/// See also [ExecutableCode] and [CodeExecutionResult] which are only
/// generated when using this tool.
///
/// See: [API Reference](https://ai.google.dev/api/caching#CodeExecution)
#[derive(Serialize, Debug, Clone, Copy)]
pub struct CodeExecution {}

/// GoogleSearch tool type.
///
/// Tool to support Google Search in Model. Powered by Google.
///
/// See: [API Reference](https://ai.google.dev/api/caching#GoogleSearch)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct GoogleSearch {

    /// Filter search results to a specific time range.
    ///
    /// If customers set a start time, they must set an end time (and
    /// vice versa).
    #[serde(skip_serializing_if = "Option::is_none")]
    pub time_range_filter: Option<Interval>,
}

/// Represents a time interval, encoded as a Timestamp start
/// (inclusive) and a Timestamp end (exclusive).
///
/// The start must be less than or equal to the end. When the start
/// equals the end, the interval is empty (matches no time). When both
/// start and end are unspecified, the interval matches any time.
///
/// See: [API Reference](https://ai.google.dev/api/caching#Interval)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct Interval {

    /// Inclusive start of the interval.
    ///
    /// If specified, a Timestamp matching this interval will have to
    /// be the same or after the start.
    ///
    /// Uses RFC 3339, where generated output will always be
    /// Z-normalized and use 0, 3, 6 or 9 fractional digits. Offsets
    /// other than "Z" are also accepted.
    ///
    /// Examples: `"2014-10-02T15:01:23Z"`,
    /// `"2014-10-02T15:01:23.045123456Z"` or
    /// `"2014-10-02T15:01:23+05:30"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub start_time: Option<String>,

    /// Exclusive end of the interval.
    ///
    /// If specified, a Timestamp matching this interval will have to
    /// be the same or after the start.
    ///
    /// Uses RFC 3339, where generated output will always be
    /// Z-normalized and use 0, 3, 6 or 9 fractional digits. Offsets
    /// other than "Z" are also accepted.
    ///
    /// Examples: `"2014-10-02T15:01:23Z"`,
    /// `"2014-10-02T15:01:23.045123456Z"` or
    /// `"2014-10-02T15:01:23+05:30"`.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub end_time: Option<String>,
}

/// Computer Use tool type.
///
/// See: [API Reference](https://ai.google.dev/api/caching#ComputerUse)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ComputerUse {

    /// The environment being operated.
    pub environment: Environment,

    /// By default, predefined functions are included in the final
    /// model call. Some of them can be explicitly excluded from being
    /// automatically included. This can serve two purposes: 1. Using
    /// a more restricted / different action space. 2. Improving the
    /// definitions / instructions of predefined functions.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub excluded_predefined_functions: Vec<String>,
}

/// Represents the environment being operated, such as a web browser.
///
/// See: [API Reference](https://ai.google.dev/api/caching#Environment)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Environment {

    /// Defaults to browser.
    EnvironmentUnspecified,

    /// Operates in a web browser.
    EnvironmentBrowser,
}

/// Tool to support URL context retrieval.
///
/// See: [API Reference](https://ai.google.dev/api/caching#UrlContext)
#[derive(Serialize, Debug, Clone, Copy)]
pub struct UrlContext {}

/// The FileSearch tool that retrieves knowledge from Semantic
/// Retrieval corpora.
///
/// Files are imported to Semantic Retrieval corpora using the
/// ImportFile API.
///
/// See: [API Reference](https://ai.google.dev/api/caching#FileSearch)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct FileSearch {

    /// The names of the fileSearchStores to retrieve from.
    ///
    /// Example: `fileSearchStores/my-file-search-store-123`.
    pub file_search_store_name: Vec<String>,

    /// Metadata filter to apply to the semantic retrieval documents
    /// and chunks.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub metadata_filter: Option<String>,

    /// The number of semantic retrieval chunks to retrieve.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub top_k: Option<i64>,
}

/// The GoogleMaps Tool that provides geospatial context for the
/// user's query.
///
/// See: [API Reference](https://ai.google.dev/api/caching#GoogleMaps)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct GoogleMaps {

    /// Whether to return a widget context token in the
    /// GroundingMetadata of the response.
    ///
    /// Developers can use the widget context token to render a Google
    /// Maps widget with geospatial context related to the places that
    /// the model references in the response.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub enable_widget: Option<bool>,
}

/// The Tool configuration containing parameters for specifying Tool
/// use in the request.
///
/// See: [API Reference](https://ai.google.dev/api/caching#ToolConfig)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct ToolConfig {

    /// Function calling config.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub function_calling_config: Option<FunctionCallingConfig>,

    /// Retrieval config.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub retrieval_config: Option<RetrievalConfig>,
}

/// Configuration for specifying function calling behavior.
///
/// See: [API Reference](https://ai.google.dev/api/caching#FunctionCallingConfig)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct FunctionCallingConfig {

    /// Specifies the mode in which function calling should
    /// execute. If unspecified, the default value will be set to
    /// AUTO.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub mode: Option<FunctionCallingMode>,

    /// A set of function names that, when provided, limits the
    /// functions the model will call.
    ///
    /// This should only be set when the Mode is ANY or
    /// VALIDATED. Function names should match
    /// [FunctionDeclaration.name]. When set, model will predict a
    /// function call from only allowed function names.
    #[serde(skip_serializing_if = "Vec::is_empty")]
    pub allowed_function_names: Vec<String>,
}

/// Defines the execution behavior for function calling by defining
/// the execution mode.
///
/// See: [API Reference](https://ai.google.dev/api/caching#Mode_1)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum FunctionCallingMode {

    /// Default model behavior, model decides to predict either a
    /// function call or a natural language response.
    Auto,

    /// Model is constrained to always predicting a function call
    /// only.
    ///
    /// If `allowed_function_names` are set, the predicted function
    /// call will be limited to any one of `allowed_function_names`,
    /// else the predicted function call will be any one of the
    /// provided `function_declarations`.
    Any,

    /// Model will not predict any function call.
    ///
    /// Model behavior is same as when not passing any function
    /// declarations.
    None,

    /// Model decides to predict either a function call or a natural
    /// language response, but will validate function calls with
    /// constrained decoding.
    Validated,
}

/// Retrieval config.
///
/// See: [API Reference](https://ai.google.dev/api/caching#RetrievalConfig)
#[derive(Serialize, Debug, Clone, Default)]
#[serde(rename_all = "camelCase")]
pub struct RetrievalConfig {

    /// The location of the user.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub lat_lng: Option<LatLng>,

    /// The language code of the user.
    ///
    /// Language code for content.
    ///
    /// Use language tags defined by BCP47.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub language_code: Option<String>,
}

impl RetrievalConfig {

    /// Create a [RetrievalConfig] from a pair of coordinates.
    pub fn new(latitude: f64, longitude: f64) -> Self {
        Self {
            lat_lng: Some(LatLng::new(latitude, longitude)),
            language_code: None,
        }
    }
}

/// An object that represents a latitude/longitude pair.
///
/// This is expressed as a pair of doubles to represent degrees
/// latitude and degrees longitude. Unless specified otherwise, this
/// object must conform to the WGS84 standard. Values must be within
/// normalized ranges.
///
/// See: [API Reference](https://ai.google.dev/api/caching#LatLng)
#[derive(Serialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct LatLng {

    /// The latitude in degrees.
    ///
    /// It must be in the range [-90.0, +90.0].
    pub latitude: f64,

    /// The longitude in degrees.
    ///
    /// It must be in the range [-180.0, +180.0].
    pub longitude: f64,
}

impl LatLng {

    /// Create a [LatLng] from a pair of coordinates.
    pub fn new(latitude: f64, longitude: f64) -> Self {
        Self { latitude, longitude }
    }
}

/// A predicted [`FunctionCall`] returned from the model that contains
/// a string representing the FunctionDeclaration.name with the
/// arguments and their values.
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct FunctionCall {

    /// The unique id of the function call.
    ///
    /// If populated, the client to execute the [FunctionCall] and
    /// return the response with the matching id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// The name of the function to call.
    pub name: String,

    /// The function parameters and values in JSON object format.
    pub args: Option<serde_json::Value>,
}

/// The result output from a [FunctionCall].
///
/// See: [API Reference](https://ai.google.dev/api/caching#FunctionResponse)
#[derive(Serialize, Deserialize, Debug, Clone)]
#[serde(rename_all = "camelCase")]
pub struct FunctionResponse {

    /// The id of the function call this response is for.
    ///
    /// Populated by the client to match the corresponding function
    /// call id.
    #[serde(skip_serializing_if = "Option::is_none")]
    pub id: Option<String>,

    /// The name of the function to call.
    pub name: String,

    /// The function response in JSON object format.
    ///
    /// Callers can use any keys of their choice that fit the
    /// function's syntax to return the function output.
    pub response: serde_json::Value,
}
