use serde::{Serialize, Deserialize};
use super::message::*;

/// A chat completion response generated by an LLM.
#[derive(Default, Debug, Clone, Serialize, Deserialize)]
pub struct Response {

    /// Chat completion messages generated by the model.
    pub messages: Vec<Message>,

    /// Usage statistics for the completion request.
    pub usage: Usage,
}

/// Usage statistics for the completion
/// [Request](super::request::Request).
#[derive(Default, Debug, Clone, Serialize, Deserialize)]
pub struct Usage {

    /// Number of tokens in the prompt.
    pub prompt_tokens: i64,

    /// Number of tokens in the generated completion.
    pub completion_tokens: i64,

    /// Total number of tokens used in the request (prompt + completion).
    pub total_tokens: i64,
}
