//! Chat completion response.

use serde::Deserialize;
use super::message::Message;

/// Chat completion response.
#[derive(Deserialize, Debug, Clone)]
pub struct Response {

    /// A unique identifier for the chat completion.
    pub id: String,

    /// A list of chat completion choices.
    pub choices: Vec<Choice>,

    /// The Unix timestamp (in seconds) of when the chat completion
    /// was created.
    pub created: u64,

    /// The model used for the chat completion.
    pub model: String,

    /// Usage statistics for the completion request.
    pub usage: Option<Usage>,
}

/// One of many possible response choices.
#[derive(Deserialize, Debug, Clone)]
pub struct Choice {

    /// The index of this choice wrt [Response::choices].
    pub index: u64,

    /// A chat completion message generated by the model.
    pub message: Option<Message>,

    /// The reason the model stopped generating tokens.
    pub finish_reason: Option<String>,

    /// Streaming delta chunk.
    pub delta: Option<Message>,
}

/// Usage statistics for a [Response].
#[derive(Deserialize, Debug, Clone)]
pub struct Usage {

    /// Number of tokens in the generated completion.
    pub completion_tokens: u64,

    /// Number of tokens in the prompt.
    pub prompt_tokens: u64,

    /// Total number of tokens used in the request
    ///
    /// prompt + completion.
    pub total_tokens: u64,
}
