[default]
description = "Default permissions for the plugin"
permissions = [
    "allow-try-connect",
    "allow-list-models",
    "allow-list-conversations",
    "allow-create-conversation",
    "allow-rename-conversation",
    "allow-remove-conversation",
    "allow-send-message",
    "allow-send-stream-message"
]